#!/usr/bin/env bash
# watcher/scan_cluster.sh

NAMESPACE="kubemind"

# 1. Capture Failed/unhealthy pods, but filter out pods generated by Jobs (names containing a hash/suffix)
kubectl get pods -n "$NAMESPACE" --no-headers 2>/dev/null \
  | awk '$3 != "Running" && $3 != "Completed" {print $1}' \
  | grep -vE "^failed-job-[a-z0-9]{5}$"

# 2. Capture Failed jobs directly by their actual owner name
kubectl get jobs -n "$NAMESPACE" -o json 2>/dev/null \
  | jq -r '.items[] | select(.status.failed >= 1) | .metadata.name'