replicaCount: 1

image:
  repository: akshayraina/kubemind-operator
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

# In charts/kubemind-operator/values.yaml
env:
  - name: OLLAMA_URL
    value: "http://host.docker.internal:11434"
  - name: MODEL_NAME
    value: "qwen3:8b"